version: '3.8'
services:
  db:
    image: devopseasylearning/banga-db:v0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    restart: always
    networks:
      - chris-net
    volumes:
      - db-data:/var/lib/mysql

  weather:
    image: devopseasylearning/banga-weather:v0.0.1
    environment:
      - APIKEY = ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    restart: always
    networks:
      - chris-net
    depends_on: 
      - db

  auth:
    image: devopseasylearning/banga-auth:v0.0.1
    environment:
      - DB_HOST=db
      - DB_PASSWORD=my-secret-pw
    restart: always
    networks:
      - chris-net
    depends_on: 
      - weather
  
  redis:
    image: redis
    restart: always
    networks:
      - chris-net
    volumes:
      - redis-data:/data
    depends_on:
      - ui

  ui:
    image: devopseasylearning/banga-ui:v0.0.1
    ports:
      - "4000:3000"
    environment:
      - AUTH_HOST=auth
      - AUTH_PORT=8080
      - WEATHER_HOST=weather
      - WEATHER_PORT=5000
      - REDIS_USER=redis
      - REDIS_PASSWORD=redis
    restart: always
    networks:
      - chris-net
    depends_on:
      - auth

networks:
  chris-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
